apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-6f4p
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-6f4p
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-6f4p
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-6f4p
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-6f4p
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vdve-tenant/rhtap-demo-app/hacbs-test-project-6f4p@sha256:a37c751eba0f7ca74a8d12829b8e4107897769a816875c8c33fa90fd5e8377f4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
